#!/bin/sh

# Populate database if not exists
test -f /data/htdocs/db/tm.sqlite || cp /data/htdocs/db_schema/tm.sqlite /data/htdocs/db/tm.sqlite

# Configure system
# Set PHP timezone
sed -i "s#PHP_TIMEZONE#${PHP_TIMEZONE}#" /etc/php5/php.ini
sed -i "s#PHP_TIMEZONE#${PHP_TIMEZONE}#" /etc/php5/cli/php.ini

# Set PHP memory limit
sed -i "s#PHP_MEMORY_LIMIT#${PHP_MEMORY_LIMIT}#" /etc/php5/php.ini
sed -i "s#PHP_MEMORY_LIMIT#${PHP_MEMORY_LIMIT}#" /etc/php5/cli/php.ini

# Set cron timeuot for engine.php
sed -i "s#CRON_TIMEOUT#${CRON_TIMEOUT}#" /var/spool/cron/crontabs/nginx
sed -i "s#CRON_COMMAND#${CRON_COMMAND}#" /var/spool/cron/crontabs/nginx

# Set owner for app directory
chown -R nginx:nginx /data/htdocs
chown -R nginx:nginx /var/log/nginx

# Write temp files by nginx
chmod 777 /tmp

# Start apps
crond
php-fpm
nginx -g 'daemon off;'
