#!/bin/sh

# Populate database if not exists
test -f /data/htdocs/db/tm.sqlite || cp /data/htdocs/db_schema/tm.sqlite /data/htdocs/db/tm.sqlite
test -f /data/htdocs/db/config.xml || cp /data/htdocs/config.xml /data/htdocs/db/config.xml

# Configure system
# Set PHP timezone
sed -i "/date\.timezone/d" /etc/php7/php.ini
echo "date.timezone = ${PHP_TIMEZONE}" >> /etc/php7/php.ini
sed -i "/date\.timezone/d" /etc/php7/cli/php.ini
echo "date.timezone = ${PHP_TIMEZONE}" >> /etc/php7/cli/php.ini

# Set PHP memory limit
sed -i "/memory_limit/d" /etc/php7/php.ini
echo "memory_limit = ${PHP_MEMORY_LIMIT}" >> /etc/php7/php.ini
sed -i "/memory_limit/d" /etc/php7/cli/php.ini
echo "memory_limit = ${PHP_MEMORY_LIMIT}" >> /etc/php7/cli/php.ini
sed -i "/memory_limit/d" /etc/php7/php-fpm.conf
echo "php_admin_value[memory_limit] = ${PHP_MEMORY_LIMIT}" >> /etc/php7/php-fpm.conf

# Set cron timeuot for engine.php
echo "${CRON_TIMEOUT} ${CRON_COMMAND}" > /etc/crontabs/nginx

# Set owner for app directory
chown -R nginx:nginx /data/htdocs
chown -R nginx:nginx /var/log/nginx

# Write temp files by nginx
chmod 777 /tmp

# Compatibility links
test -f /usr/bin/php-fpm || ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm
test -f /usr/bin/php || ln -s /usr/bin/php7 /usr/bin/php

# Start apps
crond
php-fpm
nginx -g 'daemon off;'
